apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-11T17:03:05Z"
  labels:
    author: jamshid
    last: final
    run: nginx1
  name: nginx1
  namespace: jamshid-final
  resourceVersion: "20506320"
  uid: c54c98d9-598b-41f0-a8f6-290eb5fbc325
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hfc9d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hfc9d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-11T17:03:08Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-11T17:03:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-11T17:03:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-11T17:03:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-11T17:03:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b61c963d008a3860b3a2773597c3aaf4ea695a3f00432459143bee6101dcf556
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:09369da6b10306312cd908661320086bf87fbae1b6b0c49a1f50ba531fef2eab
    lastState: {}
    name: nginx1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-04-11T17:03:07Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hfc9d
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 65.21.184.121
  hostIPs:
  - ip: 65.21.184.121
  phase: Running
  podIP: 10.233.65.170
  podIPs:
  - ip: 10.233.65.170
  qosClass: BestEffort
  startTime: "2025-04-11T17:03:06Z"
