apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-12T15:11:45Z"
  generation: 1
  labels:
    app: final-exam-host
  name: final-exam-host
  namespace: jamshid-final
  resourceVersion: "21267599"
  uid: 529067fc-ec06-4288-b0d7-33c73b261d5c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: final-exam-host
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: final-exam-host
    spec:
      containers:
      - image: nvrbckdown/flask-app:final-exam
        imagePullPolicy: IfNotPresent
        name: flask-app
        volumeMounts:
          - name: mt-volume
            mountPath: /mnt 
      volumes:
        - name: mt-volume
          hostPath:
            path: /mt  
            type:
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-12T15:11:47Z"
    lastUpdateTime: "2025-04-12T15:11:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-12T15:11:45Z"
    lastUpdateTime: "2025-04-12T15:11:47Z"
    message: ReplicaSet "final-exam-host-7866d98555" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
