apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-04-12T12:30:33Z"
  generation: 4
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: jamshid-final
  resourceVersion: "21133464"
  uid: 9fb97fcb-5ef0-477e-bf0a-a81f9074c951
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - args:
        - echo "My name is $AUTHOR and this is my $EXAM_TYPE" && sleep 1800;
        command:
        - /bin/sh
        - -c
        envFrom:
        - configMapRef:
            name: my-nginx-cm
        image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-12T12:30:35Z"
    lastUpdateTime: "2025-04-12T12:30:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-12T12:30:33Z"
    lastUpdateTime: "2025-04-12T12:48:52Z"
    message: ReplicaSet "nginx-deploy-76cf8bfc45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


  ____________________________________________

  kubectl logs nginx-deploy-76cf8bfc45-hg2wn            
My name is jamshid and this is my Final Exam
