apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-04-12T12:54:48Z"
  generation: 2
  labels:
    app: final-exam
  name: final-exam
  namespace: jamshid-final
  resourceVersion: "21144208"
  uid: 4fe02620-a8d8-44ab-ac4e-bae894066249
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: final-exam
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: final-exam
    spec:
      containers:
      - env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              key: AUTHOR
              name: my-nginx-cm
        - name: POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: nvrbckdown/flask-app:final-exam
        imagePullPolicy: IfNotPresent
        name: flask-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-12T12:54:49Z"
    lastUpdateTime: "2025-04-12T12:54:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-04-12T12:54:48Z"
    lastUpdateTime: "2025-04-12T13:03:16Z"
    message: ReplicaSet "final-exam-5d87cc9fb8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


  ____________________________________________

  Pod name:  kubectl get pods                                                         
NAME                                 READY   STATUS             RESTARTS          AGE
busybox-echo                         0/1     CrashLoopBackOff   234 (4m24s ago)   19h
final-exam-5d87cc9fb8-62fg5          1/1     Running            0                 73s
